name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Verify
    uses: maveniverse/parent/.github/workflows/ci.yml@release-38
    with:
      maven-matrix: '[ "3.9.9" ]' # the IT does mvn matrix
      maven-test: './mvnw clean verify -e -B -V -P run-its -f it'

